package ru.ozon.route256.workmanagerapi

object WorkerKey {
    const val COMMON_WORKER_TAG = "PRODUCTS_WORKER_TAG"
    const val PRODUCTS_DTO_TAG = "PRODUCTS_DTO_TAG"
    const val PRODUCTS_DETAIL_PAGE_DTO_TAG = "PRODUCTS_DETAIL_PAGE_DTO_TAG"
    const val KEY_RESPONSE_PRODUCTS_DTO = "KEY_PRODUCTS_DTO"
    const val KEY_RESPONSE_PRODUCTS_DETAIL_PAGE_DTO = "KEY_RESPONSE_PRODUCTS_DETAIL_PAGE_DTO"
}
