package ru.ozon.route256.util.const

object PreferencesConst {
    const val MAIN_PREFERENCES_NAME = "MAIN_PREFERENCES_NAME"
    const val KEY_CACHED_PRODUCTS_DTO = "KEY_CACHED_PRODUCTS"
    const val KEY_CACHED_PRODUCTS_DETAIL_PAGE_DTO = "KEY_CACHED_PRODUCTS_DETAIL_PAGE_DTO"
    const val KEY_CACHED_ADDING_PRODUCTS_DTO = "KEY_CACHED_ADDING_PRODUCTS_DTO"
    const val KEY_CACHED_ADDING_PRODUCTS_DETAIL_PAGE_DTO = "KEY_CACHED_ADDING_PRODUCTS_DETAIL_PAGE_DTO"
    const val KEY_CACHED_IN_CART_LIST = "KEY_CACHED_IN_CART_LIST"
}
